Добавление проекта
htmlacademy-php1/2000829-doingsdone-14 pull request #15
Opened 2022-05-21 01:41 UTC by Jerikho7

2022-05-21 02:31 UTC, dshemin requested changes

2022-05-21 02:31 UTC, dshemin commented on schema.sql
> -  name VARCHAR(255) NOT NULL UNIQUE,
Зачем был убран unique индекс?

2022-05-21 05:18 UTC, dshemin requested changes

2022-05-21 05:18 UTC, dshemin commented on index.php
> +$task_id = filter_input(INPUT_GET, 'id');
`task_id` должен быть, а не `id`. Имя тут должно совпадать с именем в строке запроса

2022-05-21 13:11 UTC, dshemin requested changes

2022-05-21 13:11 UTC, dshemin commented on index.php
> +$today = filter_input(INPUT_GET, 'today', FILTER_SANITIZE_SPECIAL_CHARS);
А что, если сделать просто свойство `filter` с возможными значениями, '', 'today', 'tomorrow', 'overdue'? Не придётся извлекать много разных параметров и делать развесистые if'ы.

2022-05-22 04:05 UTC, dshemin requested changes

2022-05-22 04:05 UTC, dshemin commented on index.php
> +	switch ($checked) {
Если я сначала отфильтрую, а потом нажму checked моя фильтрация пропадёт. Тоже самое и с поиском. Нужно обработать до того как мы достанем задачи для пока любым способом.

2022-05-22 07:56 UTC, dshemin requested changes

2022-05-22 07:56 UTC, dshemin commented on helpers.php
> +function  change_status($connect, $user_id, $tasks) {
А зачем нам тут `$tasks`? Мы с ней никак не работает. Будет лучше сюда явно передать `$task_id` и `$checked`.

2022-05-22 07:56 UTC, dshemin commented on index.php
> +$project_id = filter_input(INPUT_GET, 'id', FILTER_SANITIZE_SPECIAL_CHARS);
Лучше не использовать такие общие названия как `id` если у нас нет конкретного контекста. Тут удачнее будет использовать `project_id`.

2022-05-22 07:56 UTC, dshemin commented on index.php
> +$task_checked = change_status($connect, $user_id, $tasks);
Смотрите что у вас получилось: $tasks, на данном этапе, у нас пустой. Зачем нам его передавать в эту функцию чтобы она нам потом опять вернула его обратно, пустым? Он тут, как я писал в другом комментарии, вообще не нужен.

2022-05-22 07:56 UTC, dshemin commented on index.php
> +$task_checked = change_status($connect, $user_id, $tasks);
Посмотрел код ниже, вы немного не поняли. Тут надо сделать следующее:

1. Проверить что `check` был передан и имеет значение 0 или 1. Если да, то обновить указанную задачу.
2. После этого, передали нам `check` или нет, нам не важно, мы обрабатываем фильтры, поиски и т.п.

Просто не свзяывайте эти операции вместе, они не зависят друг от друга.

2022-05-22 11:18 UTC, dshemin requested changes

2022-05-22 11:18 UTC, dshemin commented on add_project.php
> +$project_name = filter_input(INPUT_GET, 'name');
Посмотрите в ТЗ:

```
Последовательность действий:

1. Проверить, что пользователь залогинен.
```

ПРоверки нет в результате чего я могу зайти на эту страницу с создать проект который не будет присоединён ни к одному пользователю.

<img width="1680" alt="Screenshot 2022-05-22 at 17 52 25" src="https://user-images.githubusercontent.com/11780307/169691735-3a8409b7-e313-446a-95dc-3946f639c28b.png">

2022-05-22 11:18 UTC, dshemin commented on add_project.php
> +$project_name = filter_input(INPUT_GET, 'name');
На странице добавления новой задачи не работает кнопка "Добавить проект"

2022-05-22 11:18 UTC, dshemin commented on helpers.php
> +        $sql = 'SELECT id, status, name, deadline_at, file, project_id FROM tasks WHERE deadline_at = CURDATE() AND user_id = ?';
Неправильно работает фильтр 'today'. У меня есть задачи на сегодня, но их не показывает в фильтре:
<img width="1680" alt="Screenshot 2022-05-22 at 18 15 41" src="https://user-images.githubusercontent.com/11780307/169692480-1dff63dc-2ba0-418d-83c4-a5d7f6b9b5dc.png">
<img width="1680" alt="Screenshot 2022-05-22 at 18 15 48" src="https://user-images.githubusercontent.com/11780307/169692485-bd312fc2-00d1-4acd-8596-07e7caa47339.png">

2022-05-22 11:49 UTC, dshemin requested changes

2022-05-22 11:49 UTC, dshemin commented on add_project.php
> +	$page_content = include_template('guest.php');
А почему бы просто не сделать редирект на ту страницу, где у нас это уже обрабатывается?

2022-05-22 11:49 UTC, dshemin commented on add_project.php
> +	$required = ['name'];
Не вижу чтобы эта переменная где-нибудь использовалась.

2022-05-22 11:49 UTC, dshemin commented on helpers.php
> +		break;
Данная строка должна быть смещена вправо и быть на одном уровне с предыдущей строкой.

2022-05-22 11:49 UTC, dshemin commented on helpers.php
> +		break;
Данная строка должна быть смещена вправо и быть на одном уровне с предыдущей строкой.

2022-05-22 11:49 UTC, dshemin commented on index.php
> +	};
Мне кажется тут лишние пробелы после  `;`

2022-05-22 11:49 UTC, dshemin commented on helpers.php
> +    switch ($filter) {
Надо бы правильно обрабатывать неожиданное значение для `$filter`. Сейчас вот что происходит:
<img width="1680" alt="Screenshot 2022-05-22 at 18 48 19" src="https://user-images.githubusercontent.com/11780307/169693742-628e97ad-1572-48a4-b62b-cf3416886aff.png">

2022-05-22 11:50 UTC, Jerikho7 commented on add_project.php
> +	$page_content = include_template('guest.php');
На  index.php что ли?

2022-05-22 11:51 UTC, dshemin commented on add_project.php
> +	$page_content = include_template('guest.php');
Да, у нас ведь там обработка, ведь так?

2022-05-23 13:55 UTC, dshemin approved these changes

2022-05-23 13:55 UTC, merged